### ISSUE TITLE
[Feature] (Course Generator) Field Corner Detection Sensitivity

### ISSUE THREAD

**Issue by nitroSkirata** [Courseplay/CourseGenerator#3]
**What is the problem this feature/enhancement solves?**
Especially on modmaps(e.g. calmsden) field corners are not 90° angles, but have such a sharp radius, that they might as well be considered as such.

**Describe the solution you'd like**
Increase the sensitivity of the corner detection, so that every radius lower then 1/2 workwidth (or maybe a user selectable value) is considered a sharp corner, when using sharp corner mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by rohne83** [comment]
One thing to add: sometimes the smooth corner driving is enough for the first headland, but for the 2nd or 3rd headland lanes it won't be enough. So maybe it should rather be checked for every lane separately if a corner can still be worked smoothly or a sharp curve with reversing is needed.
As you can see in the screenshot. The course was generated with sharp corners indeed, but since there wasn't a sharp corner necessary on outernmost lane the two inner lanes don't have a sharp corner as well, resulting in much fruit being left (and makes life harder for the unloader's pathfinder):
![fsScreen_2022_06_08_15_30_59](https://user-images.githubusercontent.com/71030138/180751793-163cd043-0fd9-4c14-aec5-856a47da6ab2.png)

**Comment by coatsy35** [comment]
This will/would be so good if it can be fixed in the new generator engine. Some of my pics today I foudn whilst clearing out my screenshot folder. All of these were sharp corners, but the nodes were not set as sharp.

![fsScreen_2023_02_15_13_36_12](https://github.com/Courseplay/CourseGenerator/assets/122838698/77e72d65-a70e-407f-a3eb-5dce38d4a85e)

Calmsden next to the yard
![fsScreen_2023_02_26_16_59_30](https://github.com/Courseplay/CourseGenerator/assets/122838698/cbebfb3b-3435-474e-b973-3c6fa90d93de)

The Oaks
![fsScreen_2023_07_08_14_11_23](https://github.com/Courseplay/CourseGenerator/assets/122838698/f6e1b6a1-2623-40ef-8afc-15374b74a36c)

![fsScreen_2023_07_09_21_38_21](https://github.com/Courseplay/CourseGenerator/assets/122838698/530f47a2-17d6-4b3c-9d70-9bc492e9779b)

![fsScreen_2023_07_19_21_43_06](https://github.com/Courseplay/CourseGenerator/assets/122838698/238ee7d4-8879-4fc0-bf00-e6677c509535)

**Comment by pvaiko** [comment]
We have now settings for:
1. Radius for sharpening a headland corner. If making a corner needs a turning radius less than this, the generator replaces the corner with a headland turn.
2. Number of rounded headlands: we can now set how many headlands will have rounded corners (all corners rounded to the turning radius of the vehicle). Rounded headlands will always be the outermost ones. For example, 7 headlands, 2 rounded:

![image](https://github.com/Courseplay/CourseGenerator/assets/2379521/8dca115f-6a32-46d1-9d52-4480a6fb443c)

**Comment by coatsy35** [comment]
That is cool. Nice. Is there a timeframe yet when we might start seeing the new generator?

**Comment by pvaiko** [comment]
Don't hold your breath. 

After all issues here are closed we'll also need some time to integrate it into the game.

**Comment by coatsy35** [comment]
Fair enough 😂

**Comment by rohne83** [comment]
That looks pretty well. Do you also have sth in mind for multitool courses? While for first tool on the outermost lane the normal "smooth" or "round" turn might be enough, this might be too narrow already for the second to fifth tool (depending on number of vehicles on course). I.e. with five tools on course, the turning radius in the corners for the last two vehicles is less than the average which I think might be considered by the generator, and thus might be as narrow already that a sharp turn is needed for these.

**Comment by coatsy35** [comment]
I would think if the combine corner turn is used on this for every tool I.e the following vehicles slow down and the wait for the one in front to turn it should be fine. But that’s just my opinion

**Comment by rohne83** [comment]
I'm not talking about collisions (that's working fine already now), but about unharvested areas due to tighter and tighter turning radius from tool to tool within the same headland pass.

**Comment by coatsy35** [comment]
You won't have any unharvested area due to the fact it used round/smooth on the outside and sharp inside if the width and turning radius does not work. IRL I would never round cay corner.  Any corner I would drill, plough or cultivate would be sharp regardless of the corner. I think this new generator takes that into account well.
